version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: bookworm_postgres_dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookworm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookworm"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  postgres_test:
    image: postgres:15
    container_name: bookworm_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookworm_test
    ports:
      - "54320:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookworm_test"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  postgres_data:
    driver: local
  postgres_test_data:
    driver: local

networks:
  default:
    name: bookworm_network
