export const ORDER_STATUS = {
  PENDING_PAYMENT: 'PENDING_PAYMENT',
  PENDING_PICKUP: 'PENDING_PICKUP',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  RETURNED: 'RETURNED'
} as const;

export const INVENTORY_STATUS = {
  IN_STOCK: 'in_stock',
  RESERVED: 'reserved',
  SOLD: 'sold',
  RETURNED: 'returned',
  DAMAGED: 'damaged',
  BULK_ACQUISITION: 'BULK_ACQUISITION'
} as const;

export const ORDER_TYPE = {
  PURCHASE: 'PURCHASE',
  SELL: 'SELL'
} as const;

export const SETTLEMENT_TYPE = {
  CASH: 'CASH',
  VOUCHER: 'VOUCHER'
} as const;

export const ERROR_CODES = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  DUPLICATE_RECORD: 'DUPLICATE_RECORD',
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  TX_RETRY_EXCEEDED: 'TX_RETRY_EXCEEDED',
  EMPTY_ITEMS: 'EMPTY_ITEMS',
  ORDER_SIZE_EXCEEDED: 'ORDER_SIZE_EXCEEDED',
  MAX_RESERVED_ITEMS_EXCEEDED: 'MAX_RESERVED_ITEMS_EXCEEDED',
  INSUFFICIENT_INVENTORY_PRECHECK: 'INSUFFICIENT_INVENTORY_PRECHECK',
  PICKUP_CODE_GEN_FAILED: 'PICKUP_CODE_GEN_FAILED',
  INVENTORY_RACE_CONDITION: 'INVENTORY_RACE_CONDITION',
  CONCURRENT_PENDING_ORDER: 'CONCURRENT_PENDING_ORDER'
} as const;

export const ERROR_MESSAGES = {
  AUTHENTICATION_REQUIRED: 'Authentication required',
  ACCESS_DENIED: 'Access denied',
  VALIDATION_FAILED: 'Request validation failed',
  RECORD_NOT_FOUND: 'Record not found',
  DUPLICATE_RECORD: 'A record with this data already exists',
  INTERNAL_ERROR: 'Internal server error',
  SYSTEM_BUSY: '系统繁忙，请稍后重试',
  NO_BOOKS_SELECTED: '没有选择任何书籍',
  BOOKS_UNAVAILABLE: '部分书籍已不可用，请刷新后重试',
  PICKUP_CODE_GENERATION_FAILED: '无法生成唯一订单取货码',
  INVENTORY_RACE: '手慢了，部分书籍已被抢购，请重新下单',
  CONCURRENT_ORDER: '您有一个正在付款的订单，请先完成付款或等待订单过期'
} as const;

export const HTTP_STATUS = {
  UNAUTHORIZED: 401,
  FORBIDDEN: 403
} as const;

export const WECHAT_CONSTANTS = {
  JSCODE2SESSION_URL: 'https://api.weixin.qq.com/sns/jscode2session',
  GET_ACCESS_TOKEN_URL: 'https://api.weixin.qq.com/cgi-bin/token',
  GET_PHONE_NUMBER_URL: 'https://api.weixin.qq.com/wxa/business/getuserphonenumber',
  GRANT_TYPE: 'authorization_code',
  SUCCESS_CODE: 'SUCCESS',
  FAIL_CODE: 'FAIL',
  SUCCESS_MESSAGE: '成功',
  RETRY_MESSAGE: '请稍后重试',
  SIGN_TYPE: 'RSA'
} as const;

export const API_CONSTANTS = {
  TANSHU_BASE_URL: 'https://api.tanshuapi.com/api/isbn/v2/index'
} as const;

export const DEFAULT_VALUES = {
  EDITION: 'default',
  UNKNOWN_TITLE: '未知书名',
  UNKNOWN_AUTHOR: '未知作者',
  UNKNOWN_PUBLISHER: '未知出版社',
  NO_SUMMARY: '暂无简介',
  ORDER_NUMBER_PREFIX: 'BOOKWORM_'
} as const;

export const BUSINESS_LIMITS = {
  MAX_REFUND_ATTEMPTS: 5,
  REFUND_BATCH_SIZE: 50,
  TRANSACTION_TIMEOUT_MS: 15000,
  AMOUNT_TO_CENTS_MULTIPLIER: 100,
  MAX_AMOUNT_CENTS: 100000000,
  CLOCK_SKEW_TOLERANCE_SECONDS: 60,
  PAYMENT_QUERY_RETRY_ATTEMPTS: 3,
  PAYMENT_QUERY_RETRY_DELAY_MS: 200,
  ADVISORY_LOCK_TIMEOUT_MS: 5 * 60 * 1000,
  DEFAULT_RETRY_ATTEMPTS: 3,
  DEFAULT_RETRY_DELAY_MS: 100,
  MAX_ACQUISITION_ITEMS: 100
} as const;

export const ENVIRONMENT_CHECKS = {
  NON_TEST_ENVIRONMENTS: ['production', 'development']
} as const;
